@echo off
cd /d E:\01-AI-Proj\task-manager\backend
echo Starting container...
docker compose up -d
echo Waiting 5 seconds...
timeout /t 5 /nobreak > nul
echo Checking container status...
docker ps -a --filter "name=backend"
echo Getting logs...
docker logs backend-backend-1
echo Testing API...
curl.exe -H "x-user-id: test-user" http://localhost:8080/api/projects